<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>error handling</title>
</head>
<body>
    <script>

        class MathUtil {

            static sum( ...numbers){
                if (numbers.length === 0){
                    throw new Error("Tidak ada nilai untuk dijumlahkan");  
                } else {
                    let total = 0;
                    for (const number of numbers) {
                        total += number;
                    }
                    return total;
                }
            }

        }


        try {
            console.info(MathUtil.sum())
            console.info(`dia mengeksekusi sampai sini aja tidak sampai catch`); // tidak sampai catch
        } catch (error) {
            console.info(`terjadi error : ${error.message}`); // catch cuma dieksekusi ketika terjadi error
        } finally {
            console.info("program selesai"); // tetap diekseskusi tidak peduli error atau tidak
        }

        // const hasil = MathUtil.sum(); // keluar error
        // // const result = MathUtil.sum(0); // hasilnya 0

        // // console.info(result);
        // console.info(hasil);

        console.info("contoh diluar error handling");


        // contoh try-finally

        class Counter {
            #counter = 0;

            next(){
                // return this.#counter;
                // this.#counter ++;        // karena diatas ada return maka this.#counter++ tidak dieksekusi
                try {
                    return this.#counter;
                } finally {
                    this.#counter ++;
                }
            }
        }

        const hitung = new Counter;
        hitung.next()
        console.info(hitung.next());

        
    </script>
</body>
</html>